[env:c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_port = COM17
monitor_port = COM17
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:webflasher]
extends = env:c3
build_flags =
    ${env:c3.build_flags}
    -DWEBFLASHER_BUILD=1
